let MODAL_KEYS = {
  POD_FORM_MODAL: 'POD_FORM_MODAL',
  PV_FORM_MODAL: 'PV_FORM_MODAL',
  SERVICE_FORM_MODAL: 'SERVICE_FORM_MODAL',
  SERVICE_GROUP_FORM_MODAL: 'SERVICE_GROUP_FORM_MODAL'
};

module.exports = MODAL_KEYS;
